// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: remap/adverts/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgCreateAdvert struct {
	Creator         string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	AdvertId        string `protobuf:"bytes,2,opt,name=advertId,proto3" json:"advertId,omitempty"`
	State           string `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	AssetId         string `protobuf:"bytes,4,opt,name=assetId,proto3" json:"assetId,omitempty"`
	Price           uint64 `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	MinRentalPeriod uint64 `protobuf:"varint,6,opt,name=minRentalPeriod,proto3" json:"minRentalPeriod,omitempty"`
	MaxRentalPeriod uint64 `protobuf:"varint,7,opt,name=maxRentalPeriod,proto3" json:"maxRentalPeriod,omitempty"`
	Conditions      string `protobuf:"bytes,8,opt,name=conditions,proto3" json:"conditions,omitempty"`
	ExpirationDate  uint64 `protobuf:"varint,9,opt,name=expirationDate,proto3" json:"expirationDate,omitempty"`
}

func (m *MsgCreateAdvert) Reset()         { *m = MsgCreateAdvert{} }
func (m *MsgCreateAdvert) String() string { return proto.CompactTextString(m) }
func (*MsgCreateAdvert) ProtoMessage()    {}
func (*MsgCreateAdvert) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec868a59471027a2, []int{0}
}
func (m *MsgCreateAdvert) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateAdvert) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateAdvert.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateAdvert) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateAdvert.Merge(m, src)
}
func (m *MsgCreateAdvert) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateAdvert) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateAdvert.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateAdvert proto.InternalMessageInfo

func (m *MsgCreateAdvert) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateAdvert) GetAdvertId() string {
	if m != nil {
		return m.AdvertId
	}
	return ""
}

func (m *MsgCreateAdvert) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *MsgCreateAdvert) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

func (m *MsgCreateAdvert) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *MsgCreateAdvert) GetMinRentalPeriod() uint64 {
	if m != nil {
		return m.MinRentalPeriod
	}
	return 0
}

func (m *MsgCreateAdvert) GetMaxRentalPeriod() uint64 {
	if m != nil {
		return m.MaxRentalPeriod
	}
	return 0
}

func (m *MsgCreateAdvert) GetConditions() string {
	if m != nil {
		return m.Conditions
	}
	return ""
}

func (m *MsgCreateAdvert) GetExpirationDate() uint64 {
	if m != nil {
		return m.ExpirationDate
	}
	return 0
}

type MsgCreateAdvertResponse struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgCreateAdvertResponse) Reset()         { *m = MsgCreateAdvertResponse{} }
func (m *MsgCreateAdvertResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateAdvertResponse) ProtoMessage()    {}
func (*MsgCreateAdvertResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec868a59471027a2, []int{1}
}
func (m *MsgCreateAdvertResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateAdvertResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateAdvertResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateAdvertResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateAdvertResponse.Merge(m, src)
}
func (m *MsgCreateAdvertResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateAdvertResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateAdvertResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateAdvertResponse proto.InternalMessageInfo

func (m *MsgCreateAdvertResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgUpdateAdvert struct {
	Creator         string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id              uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	AdvertId        string `protobuf:"bytes,3,opt,name=advertId,proto3" json:"advertId,omitempty"`
	State           string `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	AssetId         string `protobuf:"bytes,5,opt,name=assetId,proto3" json:"assetId,omitempty"`
	Price           uint64 `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
	MinRentalPeriod uint64 `protobuf:"varint,7,opt,name=minRentalPeriod,proto3" json:"minRentalPeriod,omitempty"`
	MaxRentalPeriod uint64 `protobuf:"varint,8,opt,name=maxRentalPeriod,proto3" json:"maxRentalPeriod,omitempty"`
	Conditions      string `protobuf:"bytes,9,opt,name=conditions,proto3" json:"conditions,omitempty"`
	ExpirationDate  uint64 `protobuf:"varint,10,opt,name=expirationDate,proto3" json:"expirationDate,omitempty"`
}

func (m *MsgUpdateAdvert) Reset()         { *m = MsgUpdateAdvert{} }
func (m *MsgUpdateAdvert) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateAdvert) ProtoMessage()    {}
func (*MsgUpdateAdvert) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec868a59471027a2, []int{2}
}
func (m *MsgUpdateAdvert) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateAdvert) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateAdvert.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateAdvert) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateAdvert.Merge(m, src)
}
func (m *MsgUpdateAdvert) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateAdvert) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateAdvert.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateAdvert proto.InternalMessageInfo

func (m *MsgUpdateAdvert) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgUpdateAdvert) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MsgUpdateAdvert) GetAdvertId() string {
	if m != nil {
		return m.AdvertId
	}
	return ""
}

func (m *MsgUpdateAdvert) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *MsgUpdateAdvert) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

func (m *MsgUpdateAdvert) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *MsgUpdateAdvert) GetMinRentalPeriod() uint64 {
	if m != nil {
		return m.MinRentalPeriod
	}
	return 0
}

func (m *MsgUpdateAdvert) GetMaxRentalPeriod() uint64 {
	if m != nil {
		return m.MaxRentalPeriod
	}
	return 0
}

func (m *MsgUpdateAdvert) GetConditions() string {
	if m != nil {
		return m.Conditions
	}
	return ""
}

func (m *MsgUpdateAdvert) GetExpirationDate() uint64 {
	if m != nil {
		return m.ExpirationDate
	}
	return 0
}

type MsgUpdateAdvertResponse struct {
}

func (m *MsgUpdateAdvertResponse) Reset()         { *m = MsgUpdateAdvertResponse{} }
func (m *MsgUpdateAdvertResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateAdvertResponse) ProtoMessage()    {}
func (*MsgUpdateAdvertResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec868a59471027a2, []int{3}
}
func (m *MsgUpdateAdvertResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateAdvertResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateAdvertResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateAdvertResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateAdvertResponse.Merge(m, src)
}
func (m *MsgUpdateAdvertResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateAdvertResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateAdvertResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateAdvertResponse proto.InternalMessageInfo

type MsgDeleteAdvert struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id      uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgDeleteAdvert) Reset()         { *m = MsgDeleteAdvert{} }
func (m *MsgDeleteAdvert) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteAdvert) ProtoMessage()    {}
func (*MsgDeleteAdvert) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec868a59471027a2, []int{4}
}
func (m *MsgDeleteAdvert) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteAdvert) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteAdvert.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteAdvert) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteAdvert.Merge(m, src)
}
func (m *MsgDeleteAdvert) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteAdvert) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteAdvert.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteAdvert proto.InternalMessageInfo

func (m *MsgDeleteAdvert) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgDeleteAdvert) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgDeleteAdvertResponse struct {
}

func (m *MsgDeleteAdvertResponse) Reset()         { *m = MsgDeleteAdvertResponse{} }
func (m *MsgDeleteAdvertResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteAdvertResponse) ProtoMessage()    {}
func (*MsgDeleteAdvertResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec868a59471027a2, []int{5}
}
func (m *MsgDeleteAdvertResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteAdvertResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteAdvertResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteAdvertResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteAdvertResponse.Merge(m, src)
}
func (m *MsgDeleteAdvertResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteAdvertResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteAdvertResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteAdvertResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreateAdvert)(nil), "remap.adverts.MsgCreateAdvert")
	proto.RegisterType((*MsgCreateAdvertResponse)(nil), "remap.adverts.MsgCreateAdvertResponse")
	proto.RegisterType((*MsgUpdateAdvert)(nil), "remap.adverts.MsgUpdateAdvert")
	proto.RegisterType((*MsgUpdateAdvertResponse)(nil), "remap.adverts.MsgUpdateAdvertResponse")
	proto.RegisterType((*MsgDeleteAdvert)(nil), "remap.adverts.MsgDeleteAdvert")
	proto.RegisterType((*MsgDeleteAdvertResponse)(nil), "remap.adverts.MsgDeleteAdvertResponse")
}

func init() { proto.RegisterFile("remap/adverts/tx.proto", fileDescriptor_ec868a59471027a2) }

var fileDescriptor_ec868a59471027a2 = []byte{
	// 423 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0xbf, 0x6a, 0xeb, 0x30,
	0x14, 0xc6, 0x63, 0xc7, 0xf9, 0x27, 0x72, 0x13, 0x10, 0xf7, 0x8f, 0xaf, 0x07, 0x11, 0x3c, 0x84,
	0xdc, 0xc5, 0x81, 0xdb, 0xb1, 0x53, 0xdb, 0x2c, 0x1d, 0x02, 0xc5, 0xd0, 0x0c, 0xdd, 0xd4, 0x58,
	0x04, 0x41, 0x62, 0x1b, 0x49, 0x14, 0xf7, 0x21, 0x0a, 0x7d, 0x8d, 0x3e, 0x42, 0xdf, 0xa0, 0x63,
	0xc6, 0x8e, 0x25, 0x79, 0x91, 0x62, 0xc9, 0x4e, 0x2d, 0xe3, 0xb4, 0xee, 0x64, 0xbe, 0xf3, 0x9d,
	0xf3, 0x61, 0xff, 0x2c, 0x1d, 0xf0, 0x9b, 0x91, 0x0d, 0x8e, 0xa7, 0x38, 0xb8, 0x23, 0x4c, 0xf0,
	0xa9, 0x48, 0xbc, 0x98, 0x45, 0x22, 0x82, 0x3f, 0x64, 0xdd, 0xcb, 0xea, 0x8e, 0xa3, 0xb7, 0xa9,
	0xa7, 0x6a, 0x75, 0x9f, 0x4c, 0x30, 0x9c, 0xf3, 0xd5, 0x05, 0x23, 0x58, 0x90, 0x33, 0xe9, 0x40,
	0x1b, 0x74, 0x96, 0xa9, 0x8e, 0x98, 0x6d, 0x8c, 0x8c, 0x49, 0xcf, 0xcf, 0x25, 0x74, 0x40, 0x57,
	0x4d, 0x5f, 0x06, 0xb6, 0x29, 0xad, 0x83, 0x86, 0x3f, 0x41, 0x8b, 0x0b, 0x2c, 0x88, 0xdd, 0x94,
	0x86, 0x12, 0x69, 0x16, 0xe6, 0x9c, 0xa4, 0x03, 0x96, 0xca, 0xca, 0x64, 0xda, 0x1f, 0x33, 0xba,
	0x24, 0x76, 0x6b, 0x64, 0x4c, 0x2c, 0x5f, 0x09, 0x38, 0x01, 0xc3, 0x0d, 0x0d, 0x7d, 0x12, 0x0a,
	0xbc, 0xbe, 0x22, 0x8c, 0x46, 0x81, 0xdd, 0x96, 0x7e, 0xb9, 0x2c, 0x3b, 0x71, 0xa2, 0x75, 0x76,
	0xb2, 0x4e, 0xbd, 0x0c, 0x11, 0x00, 0xcb, 0x28, 0x0c, 0xa8, 0xa0, 0x51, 0xc8, 0xed, 0xae, 0x7c,
	0x8d, 0x42, 0x05, 0x8e, 0xc1, 0x80, 0x24, 0x31, 0x65, 0x38, 0x95, 0xb3, 0xf4, 0x13, 0x7a, 0x32,
	0xa8, 0x54, 0x75, 0xff, 0x81, 0x3f, 0x25, 0x54, 0x3e, 0xe1, 0x71, 0x14, 0x72, 0x02, 0x07, 0xc0,
	0xa4, 0x81, 0xa4, 0x65, 0xf9, 0x26, 0x0d, 0xdc, 0x67, 0x85, 0xf5, 0x3a, 0x0e, 0xea, 0x60, 0x55,
	0xd3, 0x66, 0x3e, 0xad, 0x61, 0x6e, 0x1e, 0xc3, 0x6c, 0x1d, 0xc1, 0xdc, 0x3a, 0x82, 0xb9, 0xfd,
	0x05, 0xe6, 0x4e, 0x6d, 0xcc, 0xdd, 0x3a, 0x98, 0x7b, 0x35, 0x30, 0x83, 0x4a, 0xcc, 0x7f, 0x25,
	0xe6, 0x22, 0xba, 0x1c, 0xb3, 0x7b, 0x2a, 0xa9, 0xce, 0xc8, 0x9a, 0x7c, 0x9f, 0x6a, 0x96, 0x5b,
	0x1c, 0xce, 0x73, 0xff, 0x3f, 0x98, 0xa0, 0x39, 0xe7, 0x2b, 0xb8, 0x00, 0x7d, 0xed, 0x26, 0x20,
	0x4f, 0xbb, 0x49, 0x5e, 0xe9, 0xf7, 0x3b, 0xe3, 0xcf, 0xfd, 0xc3, 0xf1, 0x58, 0x80, 0xbe, 0x76,
	0x14, 0x2a, 0x72, 0x8b, 0x7e, 0x55, 0x6e, 0x15, 0x8f, 0x34, 0x57, 0x83, 0x51, 0x91, 0x5b, 0xf4,
	0xab, 0x72, 0xab, 0x78, 0x9c, 0x4f, 0x5f, 0x76, 0xc8, 0xd8, 0xee, 0x90, 0xf1, 0xb6, 0x43, 0xc6,
	0xe3, 0x1e, 0x35, 0xb6, 0x7b, 0xd4, 0x78, 0xdd, 0xa3, 0xc6, 0xcd, 0x2f, 0xb5, 0x4b, 0x92, 0x8f,
	0xa5, 0x73, 0x1f, 0x13, 0x7e, 0xdb, 0x96, 0xdb, 0xe4, 0xe4, 0x3d, 0x00, 0x00, 0xff, 0xff, 0x63,
	0xe8, 0xf9, 0xcc, 0x92, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	CreateAdvert(ctx context.Context, in *MsgCreateAdvert, opts ...grpc.CallOption) (*MsgCreateAdvertResponse, error)
	UpdateAdvert(ctx context.Context, in *MsgUpdateAdvert, opts ...grpc.CallOption) (*MsgUpdateAdvertResponse, error)
	DeleteAdvert(ctx context.Context, in *MsgDeleteAdvert, opts ...grpc.CallOption) (*MsgDeleteAdvertResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateAdvert(ctx context.Context, in *MsgCreateAdvert, opts ...grpc.CallOption) (*MsgCreateAdvertResponse, error) {
	out := new(MsgCreateAdvertResponse)
	err := c.cc.Invoke(ctx, "/remap.adverts.Msg/CreateAdvert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateAdvert(ctx context.Context, in *MsgUpdateAdvert, opts ...grpc.CallOption) (*MsgUpdateAdvertResponse, error) {
	out := new(MsgUpdateAdvertResponse)
	err := c.cc.Invoke(ctx, "/remap.adverts.Msg/UpdateAdvert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteAdvert(ctx context.Context, in *MsgDeleteAdvert, opts ...grpc.CallOption) (*MsgDeleteAdvertResponse, error) {
	out := new(MsgDeleteAdvertResponse)
	err := c.cc.Invoke(ctx, "/remap.adverts.Msg/DeleteAdvert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	CreateAdvert(context.Context, *MsgCreateAdvert) (*MsgCreateAdvertResponse, error)
	UpdateAdvert(context.Context, *MsgUpdateAdvert) (*MsgUpdateAdvertResponse, error)
	DeleteAdvert(context.Context, *MsgDeleteAdvert) (*MsgDeleteAdvertResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateAdvert(ctx context.Context, req *MsgCreateAdvert) (*MsgCreateAdvertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAdvert not implemented")
}
func (*UnimplementedMsgServer) UpdateAdvert(ctx context.Context, req *MsgUpdateAdvert) (*MsgUpdateAdvertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAdvert not implemented")
}
func (*UnimplementedMsgServer) DeleteAdvert(ctx context.Context, req *MsgDeleteAdvert) (*MsgDeleteAdvertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAdvert not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateAdvert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateAdvert)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateAdvert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/remap.adverts.Msg/CreateAdvert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateAdvert(ctx, req.(*MsgCreateAdvert))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateAdvert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateAdvert)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateAdvert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/remap.adverts.Msg/UpdateAdvert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateAdvert(ctx, req.(*MsgUpdateAdvert))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteAdvert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteAdvert)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteAdvert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/remap.adverts.Msg/DeleteAdvert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteAdvert(ctx, req.(*MsgDeleteAdvert))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "remap.adverts.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAdvert",
			Handler:    _Msg_CreateAdvert_Handler,
		},
		{
			MethodName: "UpdateAdvert",
			Handler:    _Msg_UpdateAdvert_Handler,
		},
		{
			MethodName: "DeleteAdvert",
			Handler:    _Msg_DeleteAdvert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "remap/adverts/tx.proto",
}

func (m *MsgCreateAdvert) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateAdvert) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateAdvert) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ExpirationDate != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ExpirationDate))
		i--
		dAtA[i] = 0x48
	}
	if len(m.Conditions) > 0 {
		i -= len(m.Conditions)
		copy(dAtA[i:], m.Conditions)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Conditions)))
		i--
		dAtA[i] = 0x42
	}
	if m.MaxRentalPeriod != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.MaxRentalPeriod))
		i--
		dAtA[i] = 0x38
	}
	if m.MinRentalPeriod != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.MinRentalPeriod))
		i--
		dAtA[i] = 0x30
	}
	if m.Price != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Price))
		i--
		dAtA[i] = 0x28
	}
	if len(m.AssetId) > 0 {
		i -= len(m.AssetId)
		copy(dAtA[i:], m.AssetId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.AssetId)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.State) > 0 {
		i -= len(m.State)
		copy(dAtA[i:], m.State)
		i = encodeVarintTx(dAtA, i, uint64(len(m.State)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.AdvertId) > 0 {
		i -= len(m.AdvertId)
		copy(dAtA[i:], m.AdvertId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.AdvertId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateAdvertResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateAdvertResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateAdvertResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateAdvert) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateAdvert) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateAdvert) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ExpirationDate != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ExpirationDate))
		i--
		dAtA[i] = 0x50
	}
	if len(m.Conditions) > 0 {
		i -= len(m.Conditions)
		copy(dAtA[i:], m.Conditions)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Conditions)))
		i--
		dAtA[i] = 0x4a
	}
	if m.MaxRentalPeriod != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.MaxRentalPeriod))
		i--
		dAtA[i] = 0x40
	}
	if m.MinRentalPeriod != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.MinRentalPeriod))
		i--
		dAtA[i] = 0x38
	}
	if m.Price != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Price))
		i--
		dAtA[i] = 0x30
	}
	if len(m.AssetId) > 0 {
		i -= len(m.AssetId)
		copy(dAtA[i:], m.AssetId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.AssetId)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.State) > 0 {
		i -= len(m.State)
		copy(dAtA[i:], m.State)
		i = encodeVarintTx(dAtA, i, uint64(len(m.State)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.AdvertId) > 0 {
		i -= len(m.AdvertId)
		copy(dAtA[i:], m.AdvertId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.AdvertId)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateAdvertResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateAdvertResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateAdvertResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDeleteAdvert) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteAdvert) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteAdvert) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDeleteAdvertResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteAdvertResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteAdvertResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateAdvert) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.AdvertId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.State)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.AssetId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Price != 0 {
		n += 1 + sovTx(uint64(m.Price))
	}
	if m.MinRentalPeriod != 0 {
		n += 1 + sovTx(uint64(m.MinRentalPeriod))
	}
	if m.MaxRentalPeriod != 0 {
		n += 1 + sovTx(uint64(m.MaxRentalPeriod))
	}
	l = len(m.Conditions)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.ExpirationDate != 0 {
		n += 1 + sovTx(uint64(m.ExpirationDate))
	}
	return n
}

func (m *MsgCreateAdvertResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgUpdateAdvert) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	l = len(m.AdvertId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.State)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.AssetId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Price != 0 {
		n += 1 + sovTx(uint64(m.Price))
	}
	if m.MinRentalPeriod != 0 {
		n += 1 + sovTx(uint64(m.MinRentalPeriod))
	}
	if m.MaxRentalPeriod != 0 {
		n += 1 + sovTx(uint64(m.MaxRentalPeriod))
	}
	l = len(m.Conditions)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.ExpirationDate != 0 {
		n += 1 + sovTx(uint64(m.ExpirationDate))
	}
	return n
}

func (m *MsgUpdateAdvertResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDeleteAdvert) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgDeleteAdvertResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateAdvert) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateAdvert: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateAdvert: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AdvertId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AdvertId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.State = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AssetId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			m.Price = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Price |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinRentalPeriod", wireType)
			}
			m.MinRentalPeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinRentalPeriod |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxRentalPeriod", wireType)
			}
			m.MaxRentalPeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxRentalPeriod |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Conditions", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Conditions = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpirationDate", wireType)
			}
			m.ExpirationDate = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpirationDate |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateAdvertResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateAdvertResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateAdvertResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateAdvert) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateAdvert: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateAdvert: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AdvertId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AdvertId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.State = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AssetId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			m.Price = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Price |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinRentalPeriod", wireType)
			}
			m.MinRentalPeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinRentalPeriod |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxRentalPeriod", wireType)
			}
			m.MaxRentalPeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxRentalPeriod |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Conditions", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Conditions = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpirationDate", wireType)
			}
			m.ExpirationDate = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpirationDate |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateAdvertResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateAdvertResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateAdvertResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteAdvert) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteAdvert: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteAdvert: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteAdvertResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteAdvertResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteAdvertResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
